// <auto-generated />
using System;
using Certus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certus.Infrastructure.Migrations
{
    [DbContext(typeof(CertusDbContext))]
    [Migration("20260722101829_AddStrategyMappingTable")]
    partial class AddStrategyMappingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certus.Domain.Evaluation.Entities.PerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualReturn")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DailyPnL")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Drawdown")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Equity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Sharpe")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SupposedReturn")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("PerformanceSnapshots");
                });

            modelBuilder.Entity("Certus.Domain.Execution.Aggregates.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Slippage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Certus.Domain.Platform.Aggregates.PlatformConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PortfolioDeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PlatformConnections");
                });

            modelBuilder.Entity("Certus.Domain.Platform.Aggregates.PortfolioDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EACount")
                        .HasColumnType("int");

                    b.Property<string>("EANames")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("MonitoringStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetMT4Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioDeployments");
                });

            modelBuilder.Entity("Certus.Domain.Platform.Entities.StrategyMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StrategyDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrategyExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("StrategyDefinitionId");

                    b.HasIndex("ConnectionId", "StrategyExternalId")
                        .IsUnique();

                    b.ToTable("StrategyMappings");
                });

            modelBuilder.Entity("Certus.Domain.Platform.Repositories.ImportedTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Swap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TakeProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("OpenTime");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StrategyId");

                    b.ToTable("ImportedTrades");
                });

            modelBuilder.Entity("Certus.Domain.RiskAndPortfolio.Aggregates.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMarketRegime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalPortfolioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPlatformManaged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PlatformConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TargetReturn")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TargetSharpe")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Certus.Domain.Strategy.Aggregates.StrategyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TargetReturn")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Certus.Domain.Strategy.Entities.StrategySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StrategyDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StrategyDefinitionId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("StrategyId", "PortfolioId")
                        .IsUnique();

                    b.ToTable("StrategySlots");
                });

            modelBuilder.Entity("Certus.Domain.Execution.Aggregates.Trade", b =>
                {
                    b.OwnsOne("Certus.Domain.SharedKernel.Symbol", "Symbol", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AssetClass")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AssetClass");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Symbol");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("Symbol")
                        .IsRequired();
                });

            modelBuilder.Entity("Certus.Domain.Platform.Aggregates.PlatformConnection", b =>
                {
                    b.OwnsOne("Certus.Domain.Platform.ValueObjects.PlatformConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("PlatformConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ApiKey")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ConfigApiKey");

                            b1.Property<string>("DataFormat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ConfigDataFormat");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ConfigFilePath");

                            b1.Property<string>("PlatformType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ConfigPlatformType");

                            b1.Property<int>("PollingIntervalMs")
                                .HasColumnType("int")
                                .HasColumnName("ConfigPollingIntervalMs");

                            b1.Property<int?>("Port")
                                .HasColumnType("int")
                                .HasColumnName("ConfigPort");

                            b1.Property<string>("ServerAddress")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ConfigServerAddress");

                            b1.Property<int>("StaleThresholdSeconds")
                                .HasColumnType("int");

                            b1.Property<bool>("UseFileWatcher")
                                .HasColumnType("bit")
                                .HasColumnName("ConfigUseFileWatcher");

                            b1.HasKey("PlatformConnectionId");

                            b1.ToTable("PlatformConnections");

                            b1.WithOwner()
                                .HasForeignKey("PlatformConnectionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("Certus.Domain.RiskAndPortfolio.Aggregates.Portfolio", b =>
                {
                    b.OwnsOne("Certus.Domain.SharedKernel.Money", "AllocatedCapital", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AllocatedCapital");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AllocatedCurrency");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolios");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.Navigation("AllocatedCapital")
                        .IsRequired();
                });

            modelBuilder.Entity("Certus.Domain.Strategy.Aggregates.StrategyDefinition", b =>
                {
                    b.OwnsOne("Certus.Domain.Strategy.ValueObjects.StrategyType", "Type", b1 =>
                        {
                            b1.Property<Guid>("StrategyDefinitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TypeCategory");

                            b1.Property<string>("SubType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("TypeSubType");

                            b1.HasKey("StrategyDefinitionId");

                            b1.ToTable("Strategies");

                            b1.WithOwner()
                                .HasForeignKey("StrategyDefinitionId");
                        });

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("Certus.Domain.Strategy.Entities.StrategySlot", b =>
                {
                    b.HasOne("Certus.Domain.Strategy.Aggregates.StrategyDefinition", null)
                        .WithMany("Slots")
                        .HasForeignKey("StrategyDefinitionId");

                    b.OwnsOne("Certus.Domain.Strategy.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("StrategySlotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("WeightValue");

                            b1.HasKey("StrategySlotId");

                            b1.ToTable("StrategySlots");

                            b1.WithOwner()
                                .HasForeignKey("StrategySlotId");
                        });

                    b.Navigation("Weight")
                        .IsRequired();
                });

            modelBuilder.Entity("Certus.Domain.Strategy.Aggregates.StrategyDefinition", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
